/**
 * Mock game data for layout builder preview.
 * Provides realistic test data for all scoreboard scenarios.
 */

export const mockGameData = {
  homeTeam: {
    name: 'HOME',
    score: 1,
    fouls: 4,
    timeouts: 3,
    bonus: true,
    doubleBonus: false,
    possession: false,
    color: '#c41e3a',
    hits: 0,
    errors: 0,
    cornerKicks: 0,
  },
  awayTeam: {
    name: 'AWAY',
    score: 0,
    fouls: 6,
    timeouts: 2,
    bonus: false,
    doubleBonus: true,
    possession: true,
    color: '#003f7f',
    hits: 0,
    errors: 0,
    cornerKicks: 0,
  },
  gameClock: '5:42',
  activityClock: '1:30',
  timeoutClock: '0:30',
  timeOfDay: '2:45',
  preGameClock: '15:00',
  halftimeClock: '10:00',
  periodBreakClock: '5:00',
  shotClockClock: '24',
  timerName: 'Timer Name',
  sessionName: 'Session Name',
  nextUp: 'Next Up',
  period: '3',
  shotClock: 14,
  quarter: 4,
  half: 2,
  set: 3,
  isOvertimeActive: true,
  // Football
  down: 1,
  yardsToGo: 10,
  ballOn: 35,
  // Baseball
  balls: 0,
  strikes: 0,
  outs: 0,
  firstBase: false,
  secondBase: false,
  thirdBase: false,
  onBase: '000',
  // Period/Inning scores
  gamePeriodScores: [
    { period: 1, homeScore: 0, awayScore: 0 },
    { period: 2, homeScore: 0, awayScore: 0 },
    { period: 3, homeScore: 0, awayScore: 0 },
    { period: 4, homeScore: 0, awayScore: 0 },
    { period: 5, homeScore: 0, awayScore: 0 },
    { period: 6, homeScore: 0, awayScore: 0 },
    { period: 7, homeScore: 0, awayScore: 0 },
    { period: 8, homeScore: 0, awayScore: 0 },
    { period: 9, homeScore: 0, awayScore: 0 },
  ],
  inningSlots: [
    { period: 1, homeScore: 2, awayScore: 1, isCurrentInning: false, isTopHalf: false },
    { period: 2, homeScore: 0, awayScore: 3, isCurrentInning: false, isTopHalf: false },
    { period: 3, homeScore: 0, awayScore: 0, isCurrentInning: true, isTopHalf: true },
    { period: 4, homeScore: 0, awayScore: 0, isCurrentInning: false, isTopHalf: false },
    { period: 5, homeScore: 0, awayScore: 0, isCurrentInning: false, isTopHalf: false },
    { period: 6, homeScore: 0, awayScore: 0, isCurrentInning: false, isTopHalf: false },
    { period: 7, homeScore: 0, awayScore: 0, isCurrentInning: false, isTopHalf: false },
    { period: 8, homeScore: 0, awayScore: 0, isCurrentInning: false, isTopHalf: false },
    { period: 9, homeScore: 0, awayScore: 0, isCurrentInning: false, isTopHalf: false },
  ],
  inningDisplayCount: 9,
  home_sets_won: 0,
  away_sets_won: 0,
  home_player_points: 0,
  away_player_points: 0,
  home_player_name: 'Green',
  away_player_name: 'Red',
  home_team_color: '#c41e3a',
  away_team_color: '#003f7f',
  // Penalty slots for lacrosse/hockey
  penaltySlots: {
    home: {
      count: 3,
      isState0: false,
      isState1: false,
      isState2: false,
      isState3: true,
      slot0: { jersey: 90, time: '0:45', active: true },
      slot1: { jersey: 3, time: '1:30', active: true },
      slot2: { jersey: 17, time: '2:15', active: true },
    },
    away: {
      count: 3,
      isState0: false,
      isState1: false,
      isState2: false,
      isState3: true,
      slot0: { jersey: 14, time: '1:00', active: true },
      slot1: { jersey: 22, time: '1:45', active: true },
      slot2: { jersey: 8, time: '2:30', active: true },
    },
  },
  // Shootout slots for soccer/hockey/water polo
  home_shootout_made: 2,
  away_shootout_made: 1,
  shootoutSlots: [
    { round: 1, homeActive: true, awayActive: true, homeState: 1, awayState: 0, isCurrentRound: false },
    { round: 2, homeActive: true, awayActive: true, homeState: 0, awayState: 1, isCurrentRound: false },
    { round: 3, homeActive: true, awayActive: false, homeState: 1, awayState: 0, isCurrentRound: true },
    { round: 4, homeActive: false, awayActive: false, homeState: 0, awayState: 0, isCurrentRound: false },
    { round: 5, homeActive: false, awayActive: false, homeState: 0, awayState: 0, isCurrentRound: false },
  ],
  // Leaderboard slots for player stats (includes both basketball and volleyball stats)
  leaderboardSlots: {
    home: {
      count: 6,
      isState0: false,
      isState1: false,
      isState2: false,
      isState3: false,
      isState4: false,
      isState5: false,
      isState6: true,
      slot0: { jersey: '23', name: 'M. Jordan', points: 30, fouls: 2, isTopScorer: true, active: true, aces: 5, kills: 18, blocks: 2, isTopAces: true, isTopKills: true, isTopBlocks: false },
      slot1: { jersey: '33', name: 'S. Pippen', points: 22, fouls: 3, isTopScorer: false, active: true, aces: 3, kills: 12, blocks: 4, isTopAces: false, isTopKills: false, isTopBlocks: false },
      slot2: { jersey: '91', name: 'D. Rodman', points: 8, fouls: 4, isTopScorer: false, active: true, aces: 2, kills: 8, blocks: 6, isTopAces: false, isTopKills: false, isTopBlocks: true },
      slot3: { jersey: '7', name: 'T. Kukoc', points: 12, fouls: 1, isTopScorer: false, active: true, aces: 4, kills: 6, blocks: 1, isTopAces: false, isTopKills: false, isTopBlocks: false },
      slot4: { jersey: '25', name: 'S. Kerr', points: 6, fouls: 0, isTopScorer: false, active: true, aces: 1, kills: 10, blocks: 3, isTopAces: false, isTopKills: false, isTopBlocks: false },
      slot5: { jersey: '10', name: 'B. Harper', points: 4, fouls: 1, isTopScorer: false, active: true, aces: 2, kills: 5, blocks: 2, isTopAces: false, isTopKills: false, isTopBlocks: false },
    },
    away: {
      count: 6,
      isState0: false,
      isState1: false,
      isState2: false,
      isState3: false,
      isState4: false,
      isState5: false,
      isState6: true,
      slot0: { jersey: '32', name: 'K. Malone', points: 28, fouls: 3, isTopScorer: true, active: true, aces: 4, kills: 15, blocks: 3, isTopAces: false, isTopKills: true, isTopBlocks: false },
      slot1: { jersey: '12', name: 'J. Stockton', points: 18, fouls: 2, isTopScorer: false, active: true, aces: 2, kills: 14, blocks: 5, isTopAces: false, isTopKills: false, isTopBlocks: true },
      slot2: { jersey: '4', name: 'J. Hornacek', points: 14, fouls: 1, isTopScorer: false, active: true, aces: 6, kills: 7, blocks: 2, isTopAces: true, isTopKills: false, isTopBlocks: false },
      slot3: { jersey: '53', name: 'M. Eaton', points: 4, fouls: 4, isTopScorer: false, active: true, aces: 1, kills: 9, blocks: 4, isTopAces: false, isTopKills: false, isTopBlocks: false },
      slot4: { jersey: '35', name: 'A. Carr', points: 10, fouls: 2, isTopScorer: false, active: true, aces: 3, kills: 11, blocks: 1, isTopAces: false, isTopKills: false, isTopBlocks: false },
      slot5: { jersey: '24', name: 'T. Bailey', points: 8, fouls: 0, isTopScorer: false, active: true, aces: 1, kills: 6, blocks: 3, isTopAces: false, isTopKills: false, isTopBlocks: false },
    },
  },
  // Volleyball leaderboard slots for player stats (aces, kills, blocks)
  volleyballLeaderboardSlots: {
    home: {
      count: 5,
      isState0: false,
      isState1: false,
      isState2: false,
      isState3: false,
      isState4: false,
      isState5: true,
      slot0: { jersey: '10', name: 'K. Plummer', aces: 5, kills: 18, blocks: 2, active: true, isTopAces: true, isTopKills: true, isTopBlocks: false },
      slot1: { jersey: '2', name: 'M. Ratterman', aces: 3, kills: 12, blocks: 4, active: true, isTopAces: false, isTopKills: false, isTopBlocks: false },
      slot2: { jersey: '15', name: 'T. Shoji', aces: 2, kills: 8, blocks: 6, active: true, isTopAces: false, isTopKills: false, isTopBlocks: true },
      slot3: { jersey: '8', name: 'J. Smith', aces: 4, kills: 6, blocks: 1, active: true, isTopAces: false, isTopKills: false, isTopBlocks: false },
      slot4: { jersey: '22', name: 'R. Chen', aces: 1, kills: 10, blocks: 3, active: true, isTopAces: false, isTopKills: false, isTopBlocks: false },
    },
    away: {
      count: 5,
      isState0: false,
      isState1: false,
      isState2: false,
      isState3: false,
      isState4: false,
      isState5: true,
      slot0: { jersey: '7', name: 'A. Johnson', aces: 4, kills: 15, blocks: 3, active: true, isTopAces: false, isTopKills: true, isTopBlocks: false },
      slot1: { jersey: '11', name: 'S. Williams', aces: 2, kills: 14, blocks: 5, active: true, isTopAces: false, isTopKills: false, isTopBlocks: true },
      slot2: { jersey: '3', name: 'D. Garcia', aces: 6, kills: 7, blocks: 2, active: true, isTopAces: true, isTopKills: false, isTopBlocks: false },
      slot3: { jersey: '19', name: 'M. Lee', aces: 1, kills: 9, blocks: 4, active: true, isTopAces: false, isTopKills: false, isTopBlocks: false },
      slot4: { jersey: '5', name: 'C. Brown', aces: 3, kills: 11, blocks: 1, active: true, isTopAces: false, isTopKills: false, isTopBlocks: false },
    },
  },
};

export const mockBannerData = {
  entries: [
    {
      id: 1,
      image: { url: 'https://via.placeholder.com/300x100/FF0000/FFFFFF?text=Banner+1' },
      rotation_interval: 3,
    },
    {
      id: 2,
      image: { url: 'https://via.placeholder.com/300x100/00FF00/FFFFFF?text=Banner+2' },
      rotation_interval: 3,
    },
    {
      id: 3,
      image: { url: 'https://via.placeholder.com/300x100/0000FF/FFFFFF?text=Banner+3' },
      rotation_interval: 3,
    },
  ],
};
